# Generated by Django 3.1.1 on 2020-09-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desktop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Item ready to be purchased'), ('SOLD', 'Item Sold'), ('RESTOCKING', 'Item restocking in a few days'), ('IN-USE', 'Item is being used by employee')], default='SOLD', max_length=10)),
                ('issues', models.CharField(default='No issues', max_length=100)),
                ('user', models.CharField(default='USER', max_length=100)),
                ('location', models.CharField(default='ENTER LOCATION', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Item ready to be purchased'), ('SOLD', 'Item Sold'), ('RESTOCKING', 'Item restocking in a few days'), ('IN-USE', 'Item is being used by employee')], default='SOLD', max_length=10)),
                ('issues', models.CharField(default='No issues', max_length=100)),
                ('user', models.CharField(default='USER', max_length=100)),
                ('location', models.CharField(default='ENTER LOCATION', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Item ready to be purchased'), ('SOLD', 'Item Sold'), ('RESTOCKING', 'Item restocking in a few days'), ('IN-USE', 'Item is being used by employee')], default='SOLD', max_length=10)),
                ('issues', models.CharField(default='No issues', max_length=100)),
                ('user', models.CharField(default='USER', max_length=100)),
                ('location', models.CharField(default='ENTER LOCATION', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Item ready to be purchased'), ('SOLD', 'Item Sold'), ('RESTOCKING', 'Item restocking in a few days'), ('IN-USE', 'Item is being used by employee')], default='SOLD', max_length=10)),
                ('issues', models.CharField(default='No issues', max_length=100)),
                ('user', models.CharField(default='USER', max_length=100)),
                ('location', models.CharField(default='ENTER LOCATION', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
