# Generated by Django 3.1.1 on 2020-09-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20200910_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desktop',
            name='partNumber',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='partNumber',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='partNumber',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='partNumber',
        ),
        migrations.AddField(
            model_name='desktop',
            name='assetNum',
            field=models.CharField(default='ASSET NUMBER', max_length=20),
        ),
        migrations.AddField(
            model_name='equipment',
            name='assetNum',
            field=models.CharField(default='ASSET NUMBER', max_length=20),
        ),
        migrations.AddField(
            model_name='laptop',
            name='assetNum',
            field=models.CharField(default='ASSET NUMBER', max_length=20),
        ),
        migrations.AddField(
            model_name='mobile',
            name='assetNum',
            field=models.CharField(default='ASSET NUMBER', max_length=20),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Item is available for use'), ('OUT OF ORDER', 'Item is not working properly'), ('IN-USE', 'Item is being used by employee'), ('DECOMMISSIONED', 'Item has been decommissioned')], default='AVAILABLE', max_length=15),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Item is available for use'), ('OUT OF ORDER', 'Item is not working properly'), ('IN-USE', 'Item is being used by employee'), ('DECOMMISSIONED', 'Item has been decommissioned')], default='AVAILABLE', max_length=15),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Item is available for use'), ('OUT OF ORDER', 'Item is not working properly'), ('IN-USE', 'Item is being used by employee'), ('DECOMMISSIONED', 'Item has been decommissioned')], default='AVAILABLE', max_length=15),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Item is available for use'), ('OUT OF ORDER', 'Item is not working properly'), ('IN-USE', 'Item is being used by employee'), ('DECOMMISSIONED', 'Item has been decommissioned')], default='AVAILABLE', max_length=15),
        ),
    ]
